services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ default
      - '15672:15672' # RabbitMQ management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    env_file: .env
    networks:
      - mynth-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s

  service-a:
    build:
      context: .
      dockerfile: ./services/service-a/Dockerfile
    ports:
      - '3001:3001'
    env_file: .env
    networks:
      - mynth-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - NODE_ENV=production

  service-b:
    build:
      context: .
      dockerfile: ./services/service-b/Dockerfile
    ports:
      - '3002:3002'
    env_file: .env
    networks:
      - mynth-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - NODE_ENV=production

networks:
  mynth-network:
    driver: bridge
